### ISSUE TITLE
Write CF Curl hurdle

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/watchful#11]
Cloud Foundry Curl hurdle:
- [ ] **Prepare** prepare a CF app to be pushed and push it
- [ ] **Before** n/a
- [ ] **Test** curl it
- [ ] **After** n/a
- [ ] **Cleanup** delete app including routes, and delete possible file artifacts

**Comment by LynxPlay101** [comment]
If the curl merkhet needs to push it's own app, what are we passing the Domain parameter for ? 
The APIEndpoint is used for the cf-cli, but I though the Domain will be the one we run the curl aginst ?
