### ISSUE TITLE
Write basic setup logic for hurdles

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/watchful#19]
Write basic setup code that create a new Cloud Foundry org for the test run. The tool has to make sure that no matter what happens, it will eventually delete the org at the end. This also includes a hard exit of the program. If possible, catch Ctrl-C events as well.

**Comment by LynxPlay101** [comment]
https://stackoverflow.com/questions/11268943/is-it-possible-to-capture-a-ctrlc-signal-and-run-a-cleanup-function-in-a-defe
