### ISSUE TITLE
Spike: Find a suitable name for the project

### ISSUE THREAD

**Issue by LynxPlay101** [homeport/watchful#30]
The disrupt-o-meter is somewhat of a clunky name and not too fun to pronounc.

This issue finds a new name for the project that should be related to change/measurment

**Comment by LynxPlay101** [comment]
Avaria = Breakdown in Galician, as we kinda try to break the cf instance down ? idk liked the sound 

Janus = God of change/transition ?

**Comment by qu1queee** [comment]
watchful,
wakeful,
wary,
ambit,
xo,
iris,

**Comment by HeavyWombat** [comment]
olaf3000

**Comment by HeavyWombat** [comment]
[Poll in Slack](https://ibm-cloudplatform.slack.com/archives/C1NKWRQUD/p1548669693030200)

**Comment by LynxPlay101** [comment]
Fixed by #44
