### ISSUE TITLE
Rename project to watchful

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/watchful#41]
The poll indicates that `watchful` is the name to go. Switch the project to `watchful` including any text references in files.

**Comment by LynxPlay101** [comment]
@HeavyWombat I would like to have all other open pull requests merged, prior to the rename. Please ping me here once you updated the project name on github, so I can repull the project into my local repository to prevent errors after changing the import paths

**Comment by qu1queee** [comment]
rename rename rename!!

**Comment by LynxPlay101** [comment]
@qu1queee can you rename the repository to `watchful` after merging the two open PRs ? I would like to get this done today and I never did a refactor in golang, so I may run into a few issues.

**Comment by qu1queee** [comment]
@LynxPlay101 can you make sure that after the repo rename, everything is fine? please take care of all renames that need to take place.
